# Generated by Django 4.0.6 on 2022-07-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='profesion',
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(default='1960-1-1'),
            preserve_default=False,
        ),
    ]
